### ISSUE TITLE
한글이 깨지는 이유랑 해결방법 고민

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#102]
- 파일 업로드를 하면 한글의 경우 글자가 깨지는 버그가 있습니다.
- <img width="820" alt="Screen Shot 2024-01-16 at 9 22 57 PM" src="https://github.com/gyuseuyunhu/server/assets/108771739/a7514bc2-db47-4a66-aa30-0606bd3323c6">

- 원인은 한글은 인코딩 방식이 utf-8인데 그 방식을 추가하지 않아서 입니다
- 예를 들어서 content-type: text/html; charset=UTF-8
- 이런식으로 charset=UTF-8를 content-type 뒤에 추가하면 한글도 정상적으로 나옵니다

- 이걸 추가하기 제일 쉬운데가 initMimeType()입니다
-  mMimeType[".html"] = "text/html"; 대신  mMimeType[".html"] = "text/html; charset=UTF-8"; 추가하면 됩니다
- 하지만 어떤 mimeType이든 mime 뒤에 ; charset=UTF-8를 붙여도 되는지에 대한 고민이 있습니다.
-

**Comment by YunjooCho** [comment]
<img width="617" alt="image" src="https://github.com/gyuseuyunhu/server/assets/73283078/cc809d76-02e8-47f8-ab27-15e11600bb0b">

확인 결과 위의 MIME Type에 필요한 것 같습니다
