### ISSUE TITLE
http_block, server_block, location_block 상속 문제 

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#12]
각각의 block이 지시어가 중복되면 하위 클래스에 있는것으로 바뀐다
그래서 상속관계를 이용하면 쉽게 해결될것이라 생각함

하지만 지금 짠 로직으로는 불가능 해짐
로직:
config 객체에서 각각의 block을 만드는데 유효성 검사를 해서 block들에게 넣어준다
이때 http_block을 먼저 생성하고 server_block의 경우 생성자 매개변수로 http_block을 받고 그 외 server_block의 변수들을 받음
즉 server_block의 생성자는 단순히 대입만 하는 역할
부모 변수를 바꾸려면 생성자에서 해줘야 함

해결법:
config에서 block을 만드는 로직을 각각의 block 생성자가 가져가기 - hujeong
집가면서 생각한 단점: config의 객체에 있는 파싱부를 전부 각각의 block에 넣어야 해서 클래스가 커진다
장점: 아직은 이거말고 해결방법이 없는듯(상속관계를 없애지 않는한)
setter 사용(비추)

**Comment by heehoh** [comment]
매개변수는 네개까지만!

**Comment by guune** [comment]
생성자 매개변수의 갯수는 클래스 매개변수의 갯수라서 넘어걸꺼같아요

**Comment by guune** [comment]
> 매개변수는 네개까지만!


생성자 매개변수의 갯수는 클래스 매개변수의 갯수라서 넘어걸꺼같아요

**Comment by guune** [comment]
`#ifndef BLOCKBUILDER_HPP
#define BLOCKBUILDER_HPP

#include <string>
#include <vector>
#include "HttpBlock.hpp"
#include "ServerBlock.hpp"
#include "LocationBlock.hpp"
#include "ServerDirective.hpp"
#include "LocationDirective.hpp"

class BlockBuilder {
private:
    std::string root;
    std::vector<std::string> indexs;
    std::string errorPage;
    unsigned int clientMaxBodySize;
    unsigned int port;
    std::string serverName;

    ServerDirective serverDirective;
    LocationDirective locationDirective;

public:
    BlockBuilder();
    void parseConfig(const std::string& configString, const std::string& blockType);
    HttpBlock buildHttpBlock() const;
    ServerBlock buildServerBlock() const;
    LocationBlock buildLocationBlock() const;

private:
    void updateValue(const std::string& key, const std::string& value, const std::string& blockType);
};

#endif // BLOCKBUILDER_HPP
`
`#include "BlockBuilder.hpp"
#include <sstream>
#include <iostream>

BlockBuilder::BlockBuilder() : root(""), clientMaxBodySize(0), port(0) {}

void BlockBuilder::parseConfig(const std::string& configString, const std::string& blockType) {
    std::istringstream iss(configString);
    std::string key, value;

    while (iss >> key >> value) {
        try {
            if (blockType == "ServerBlock") {
                serverDirective.checkDirective(key);
            } else if (blockType == "LocationBlock") {
                locationDirective.checkDirective(key);
            }
            updateValue(key, value, blockType);
        } catch (const std::runtime_error& e) {
            std::cerr << "Error: " << e.what() << std::endl;
        }
    }
}

void BlockBuilder::updateValue(const std::string& key, const std::string& value, const std::string& blockType) {
    // Update logic...
}

HttpBlock BlockBuilder::buildHttpBlock() const {
    return HttpBlock(root, indexs, errorPage, clientMaxBodySize);
}

ServerBlock BlockBuilder::buildServerBlock() const {
    return ServerBlock(buildHttpBlock(), port, serverName);
}

LocationBlock BlockBuilder::buildLocationBlock() const {
    // Implement if necessary...
}
`

**Comment by guune** [comment]
``#ifndef BLOCKBUILDER_HPP
#define BLOCKBUILDER_HPP

#include <string>
#include <vector>
#include "HttpBlock.hpp"
#include "ServerBlock.hpp"
#include "LocationBlock.hpp"
#include "ServerDirective.hpp"
#include "LocationDirective.hpp"

class BlockBuilder {
private:
    std::string root;
    std::vector<std::string> indexs;
    std::string errorPage;
    unsigned int clientMaxBodySize;
    unsigned int port;
    std::string serverName;

    ServerDirective serverDirective;
    LocationDirective locationDirective;

public:
    BlockBuilder();
    void parseConfig(const std::string& configString, const std::string& blockType);
    HttpBlock buildHttpBlock() const;
    ServerBlock buildServerBlock() const;
    LocationBlock buildLocationBlock() const;

private:
    void updateValue(const std::string& key, const std::string& value, const std::string& blockType);
};

#endif // BLOCKBUILDER_HPP


``#include "BlockBuilder.hpp"
#include <sstream>
#include <iostream>

BlockBuilder::BlockBuilder() : root(""), clientMaxBodySize(0), port(0) {}

void BlockBuilder::parseConfig(const std::string& configString, const std::string& blockType) {
    std::istringstream iss(configString);
    std::string key, value;

    while (iss >> key >> value) {
        try {
            if (blockType == "ServerBlock") {
                serverDirective.checkDirective(key);
            } else if (blockType == "LocationBlock") {
                locationDirective.checkDirective(key);
            }
            updateValue(key, value, blockType);
        } catch (const std::runtime_error& e) {
            std::cerr << "Error: " << e.what() << std::endl;
        }
    }
}

void BlockBuilder::updateValue(const std::string& key, const std::string& value, const std::string& blockType) {
    // Update logic...
}

HttpBlock BlockBuilder::buildHttpBlock() const {
    return HttpBlock(root, indexs, errorPage, clientMaxBodySize);
}

ServerBlock BlockBuilder::buildServerBlock() const {
    return ServerBlock(buildHttpBlock(), port, serverName);
}

LocationBlock BlockBuilder::buildLocationBlock() const {
    // Implement if necessary...
}

**Comment by guune** [comment]
```
#ifndef BLOCKBUILDER_HPP
#define BLOCKBUILDER_HPP

#include <string>
#include <vector>
#include "HttpBlock.hpp"
#include "ServerBlock.hpp"
#include "LocationBlock.hpp"
#include "ServerDirective.hpp"
#include "LocationDirective.hpp"

class BlockBuilder {
private:
    std::string root;
    std::vector<std::string> indexs;
    std::string errorPage;
    unsigned int clientMaxBodySize;
    unsigned int port;
    std::string serverName;

    ServerDirective serverDirective;
    LocationDirective locationDirective;

public:
    BlockBuilder();
    void parseConfig(const std::string& configString, const std::string& blockType);
    HttpBlock buildHttpBlock() const;
    ServerBlock buildServerBlock() const;
    LocationBlock buildLocationBlock() const;

private:
    void updateValue(const std::string& key, const std::string& value, const std::string& blockType);
};

#endif // BLOCKBUILDER_HPP
```


```
#include "BlockBuilder.hpp"
#include <sstream>
#include <iostream>

BlockBuilder::BlockBuilder() : root(""), clientMaxBodySize(0), port(0) {}

void BlockBuilder::parseConfig(const std::string& configString, const std::string& blockType) {
    std::istringstream iss(configString);
    std::string key, value;

    while (iss >> key >> value) {
        try {
            if (blockType == "ServerBlock") {
                serverDirective.checkDirective(key);
            } else if (blockType == "LocationBlock") {
                locationDirective.checkDirective(key);
            }
            updateValue(key, value, blockType);
        } catch (const std::runtime_error& e) {
            std::cerr << "Error: " << e.what() << std::endl;
        }
    }
}

void BlockBuilder::updateValue(const std::string& key, const std::string& value, const std::string& blockType) {
    // Update logic...
}

HttpBlock BlockBuilder::buildHttpBlock() const {
    return HttpBlock(root, indexs, errorPage, clientMaxBodySize);
}

ServerBlock BlockBuilder::buildServerBlock() const {
    return ServerBlock(buildHttpBlock(), port, serverName);
}

LocationBlock BlockBuilder::buildLocationBlock() const {
    // Implement if necessary...
}
```
```
#include <iostream>
#include <string>
#include <vector>
#include "BlockBuilder.hpp" // 여기에 BlockBuilder 클래스가 정의되어 있어야 합니다.

int main() {
    BlockBuilder builder;

    // 예제 데이터
    std::string httpStr = "root /var/www/html; index index.html;";
    std::pair<std::string, std::vector<std::string>> serverAndLocations;

    // 서버 설정
    serverAndLocations.first = "root /var/www/example; listen 80; server_name example.com;";

    // 위치 설정
    serverAndLocations.second.push_back("location /images { root /var/www/images; autoindex on; }");
    serverAndLocations.second.push_back("location /videos { root /var/www/videos; autoindex off; }");

    // HTTP 블록 파싱 및 생성
    builder.parseConfig(httpStr, "HttpBlock");
    HttpBlock httpBlock = builder.buildHttpBlock();

    // 서버 블록 파싱 및 생성
    builder.parseConfig(serverAndLocations.first, "ServerBlock");
    ServerBlock serverBlock = builder.buildServerBlock();

    // 각 위치 블록 파싱 및 생성
    std::vector<LocationBlock> locationBlocks;
    for (const std::string& locationStr : serverAndLocations.second) {
        builder.parseConfig(locationStr, "LocationBlock");
        LocationBlock locationBlock = builder.buildLocationBlock();
        locationBlocks.push_back(locationBlock);
    }

    // 생성된 블록들의 정보 출력 (예제 출력 로직)
    // printBlockInfo(httpBlock, serverBlock, locationBlocks); // 이 함수는 블록 정보를 출력하는 함수입니다.

    return 0;
}
```

**Comment by guune** [comment]
결국 문제는 자식클래스의 맴버변수를 다 파싱하고 나서 그 결과에 따라 부모 클래스 변수도 바꿔줘야 한다는 것이였음
즉 server을 예를 들면 이 뒤는 밥먹고 작성할께요

**Comment by guune** [comment]
결국 자식 block들을 생성할때 자식의 맴버변수들이 파싱이 되고 나서 부모 block이랑 같이 생성한다는게 문제였음
그걸 위해 각각 block 생성자 내부에 파싱을 넣을까 생각했지만
1. 생성자가 하는일이 커진다(block 클래스들이 하는일이 많아짐)
2. 파싱이 중복되는 부분이 있는데 block 마다 지시어가 조금씩 달라서 생성자 마다 다 만들어 줘야 한다.

그래서 개인적으로 찾아보니 생성하는 타이밍을 내가 원하는대로 그리고 여러 매개변수가 있다면 좀 더 실수 하지 않게 생성할 수 있는 빌더 패턴을 알게 됨

그걸 토대로 일단 BlockBuilder 을 만들어봄

**Comment by heehoh** [comment]
BlockBuilder 와서 설명해주세요 😀
