### ISSUE TITLE
README 작성

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#120]
README에 어떤것을 작성하면 좋을지 댓글로 부탁드립니다!

**Comment by heehoh** [comment]
HTTP 프로토콜

Multiplexing 소켓프로그래밍

conf

가상 호스팅

정적 서버

동적처리 CGI

처리 흐름 표

이벤트 객체

**Comment by guune** [comment]
어려웠던 부분 + 해결한 부분(이슈, 풀리퀘 참고)

**Comment by YunjooCho** [comment]
클래스 다이어그램

참고자료
