### ISSUE TITLE
Parse 클래스 pair vector 리펙토링

### ISSUE THREAD

**Issue by heehoh** [gyuseuyunhu/server#18]
- Parse 객체가 pair(severStr, std::vector<locationStr>) vector를 자료구조로 사용하고 있는데, severInfo class vector로 리펙토링 할겁니다.
- Config 클래스도 Parse객체의 문자열을 받아서 사용하는데 이것도 리펙토링 합니다.

**Comment by guune** [comment]
굿 머지한것 확인했습니다.
