### ISSUE TITLE
HTTP 메시지 사용할 헤더명 정리하기

### ISSUE THREAD

**Issue by YunjooCho** [gyuseuyunhu/server#21]
p52
[요청 메시지]
 - **HTTP 메서드**
   - 값 : GET, POST, DELETE (Subject 명시)
 - **요청 URL**
 - **HTTP 버전**
   - 값 : HTTP/1.1 (Subject 명시된 버전, 고정값)
 - **Host**
 - **Context-Length**
   - 본문의 길이
   - GET인 경우 0일 수 있음 
   - 값 : 숫자
 - **Connection ※**
   - 사용여부 상의 필요 (HTTP 1.1 버전은 default? HTTP 완벽 가이드 p112)
   - 값 : keep-alive, close

[응답 메시지]
 -  **HTTP 버전**
    - 값 : HTTP/1.1 (Subject 명시된 버전, 고정값)
 - **상태 코드  ※**
    - 요청 처리에 대한 결과값
    - 사용할 상태 코드 별도 상의 예정
    - 값 : 숫자
 - **사유 구절 ※**
    - 상태 코드를 사람이 이해할 수 있도록 문자열로 표시한 것
    - 상태코드와 함께 사용할 사유구절 별도 상의 예정
    - 값 : 문자열
  - **Context-Length**
    - 본문의 길이
    - GET인 경우 0일 수 있음 
    - 값 : 숫자
  - **Context-Type ※**
    - 본문의 타입
    - 사용여부 상의 필요
    - 값 : text/html, multipart/form-data
 - **Connection ※**
    - 사용여부 상의 필요 (HTTP 1.1 버전은 default? HTTP 완벽 가이드 p112)
    - 값 : keep-alive, close
 - **Transfer-Encoding ※**
    - 사용여부 상의 필요
    - 값 : chunked

[참고]
 - https://developer.mozilla.org/ko/docs/Web/HTTP/Messages

**Comment by heehoh** [comment]
요청 메세지에 따라 request 클래스 만들기
- HTTP 메서드, 요청 URL, HTTP 버전은 각각 변수로
- 헤더는 Map<std::string, std::string>으로 저장
- 본문은 미정
