### ISSUE TITLE
파싱 전 server_block, location_block 지시어 정하기

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#3]
- [ ] sever_block 허용되는 지시어 및 중복 여부 정하기
- [ ] location_block 허용되는 지시어 및 중복 여부 정하기

**Comment by YunjooCho** [comment]
[Server_block]
- listen
- server_name
- root
- error_page
- index
- client_max_body_size
-

**Comment by guune** [comment]
[Server_block]
- 중복 여부
- listen

- server_name

- root

- error_page
    - 중복 가능
    - 사용 예시
        - error_page 404 /404.html;
       - error_page 500 502 503 504 /50x.html;
- index

- client_max_body_size

**Comment by heehoh** [comment]
- location 블록 지시어들
  
  -  엔진엑스는 location 블록을 정의하면서 요청된 URL와 비교할 패턴을 지정한다.
    - 예시 location /home/ {
    - 패턴은 폴더 구조를 따라야 함.
    - 패턴 앞에는 위치 조정 부호라는 기호가 오는데 생략가능 하지만 패턴의 성격을 지정할 때도 쓰인다고 함
    - Define a list of accepted HTTP methods for the route.
    
  - return [HTTP 상태 코드] [응답 본문]
    - Define a HTTP redirection.

**Comment by guune** [comment]
[Http_block]
- error_page
   - http, server, location 허용
    - 중복 가능
    - 사용 예시
        - error_page 404 /404.html;
          error_page 500 502 503 504 /50x.html;
- index
   - http, server, locaiton 허용
   - 중복 가능
   - 사용 예시
       - index index.html index.htm;
- client_max_body_size
   - http, server, location 허용
   - 중복 불가능 :)
   - "client_max_body_size" directive is duplicate 이런 에러뜸 
- autoindex
   - http, server, location 허용
  - 중복 불가능 :>>
  - autoindex" directive is duplicate 이런 에러 뜸
