### ISSUE TITLE
클래스 구조 정리하기

### ISSUE THREAD

**Issue by YunjooCho** [gyuseuyunhu/server#4]

**Comment by YunjooCho** [comment]
[ 클래스 전체 구조 및 관계 정리하기 ]



![Image](https://github.com/gyuseuyunhu/server/assets/73283078/91e1a057-f3d8-4dc0-8c9e-461af8b59c7d)

1. 상기 구조로 이해했는데 맞는 지?
2. Config 클래스 == Server 클래스?

**Comment by guune** [comment]
1. config 객체 생성자에서 nginx.conf 파일을 파싱을 해서 server_block, loaction_block를 만든다.
2. serverManger 객체에는 server벡터가 있어서 생성자에서 매개변수로 config 객체를 받거나 createServer 같은 메서드에서 매개변수로 config 받는다 그 후 server 객체를 만들어서 serverManger객체의 server 벡터에 push_back 해준다
3. server 객체에는 map이 존재해서 <string(server_name), location_block<>>이 존재 하고 http 요청이 들어오면 포트로 맞는 서버 객체를 찾는다 그 후 서버 객체 안에 있는 map에서 find로 location_block를 찾는다.

**Comment by heehoh** [comment]
1. 최종적으로는 kevent를 돌리면서 웹서버를 동작시켜야 하니 kqeue를 돌릴 때 어떤 자료가 필요할지 생각하고 파싱하기. read 이벤트일 때, write 이벤트일 때, cgi 이벤트 일 때 필요한 데이터가 다를 것 같다.
2. GET, POST, DELETE도 어떻게 처리해야 되는지 생각해야 한다.

**Comment by YunjooCho** [comment]
![Image](https://github.com/gyuseuyunhu/server/assets/73283078/08e9ff1a-5a9a-4687-a07f-3929b2e5b291)

**Comment by guune** [comment]
![IMG_2045](https://github.com/gyuseuyunhu/server/assets/108771739/cb719574-16d0-465a-bcae-4dd4bb48b5cf)

**Comment by guune** [comment]
#12 
에 다시 config 파싱 구조 정리 했습니다.

**Comment by heehoh** [comment]
## 예상 main문
```
int main(int ac, char** av)
{
	try 
	{
		Parse(av[1]);
		Config::createInstance(Parse.getHttpStr(), Parse.getSeverInfoStrs()); 
		ServerManger sm(Config::getServerInfos());
	}
	catch (std::exception &e)
	{
		std::cout << e.what() << std::endl;
		return 1;
	} 
	sm.run();
	return 0;
}				
```	

## 클래스 및 클래스의 역할
### Config 
- ServerInfo를 파싱하고 ServerManager에 전달

### ServerManager
- 서버들을 생성, 벡터에 담아둠.
- 다른 포트를 갖고 있을 때는 server를 server 벡터에 push_back. 
- 같은 포트 다른 서버면 serverInfo에 추가,
- 같은 포트 같은 서버이름일 때는 에러
- 서버 바인딩 에러
- 생성된 서버들을 Kqueue에 등록

### Server
- SeverInfo 벡터를 소유 
- -> 같은 포트 다른 서버들을 가지고 있음

### ServerInfo
- ServerBlock,
- locationBlock 벡터를 가지고 있음.
 
### Kqueue
- kqueue 파일디스크립터, kqueue에 등록할 이벤트, 처리할 이벤트를 관리해주는 static class

### AEvent
- Accept, Read, Write 이벤트를 담을 추상 클래스
- 내부 로직을 handle 메소드로 처리
