### ISSUE TITLE
Response 클래스 활용 리펙토링

### ISSUE THREAD

**Issue by heehoh** [gyuseuyunhu/server#51]
- [event 클래스가 너무 많이 인자를 받음](https://github.com/gyuseuyunhu/server/blob/84929dcdc81c915fcdb8807c5894e97aee20f335/src/event/ReadFileEvent.cpp#L8)
- Response 클래스를 넘겨주면 좀 더 깔끔해질 것 같아요

**Comment by YunjooCho** [comment]
### AEvent클래스를 상속받는 클래스 생성자 리팩토링!!!
#### 1. WriteEvent class
-> WriteEvent(const Server &server, int clientSocket, std::string message)에서 message 대신 미리 완성된 response을 넣어준다
-> WriteEvent 생성자 내부에서는 mMessage = mResponse.toStr()(구현 예정)을 호출해서 message를 만든다 
-> 장점은 reponse을 넣어줬기 때문에 response 헤더에서 필요한값을 얻기 편하다(지금은 Connection-type같은것)
#### 2 ReadFileEvent class
-> ReadFileEvent(const Server &server, int clientSocket, int fileFd, int fileSize, int mHttpStatusCode); 에서 fileSize, code 같은것을 토대로 response 시작줄, 헤더만 만들고 생성자로 넣어준다
-> ReadFileEvent에서 read를 한 값은 mResponse.addBody(std::string body)(구현예정)로 만들어 준다.
-> 장점은 ReadFileEvent의 생성자 매개변수를 6개를 4개로 줄일수 있음, 추후 Response 헤더, 시작줄 활용 가능하다.
