### ISSUE TITLE
파일 업로드 처리하기(GET/POST)

### ISSUE THREAD

**Issue by YunjooCho** [gyuseuyunhu/server#53]
### 1. Configuration File
 - Location Block 2개 추가
  - path : /upload (uploadForm을 보여주는 화면, GET 허용)
  - path : /uploadFile (uploadForm에서 전달받은 Body를 처리할 부분, POST만 허용)

### 2. HTTP Request Message 파싱  
[ 업로드 폼 ]
- 301 리다이렉션 /uploadFile -> 리다이렉션은 현재 처리 됨(왜 되는 지 이해하기)
- 입력받은 내용을 리다이렉션 할 때 본문을 추가하는 로직 처리 필요
- 처리 부분 : ReadRequestEvent::makeResponseEvent() 로직 추가, Request::addBody() 메서드 새로 생성
- mResponse.addHead("Location", oss.str()) 부분에서 getHost()로 /upload 이면 addBody() 메서드를 통해 Form으로 받은 파일의 바이너리(?) 코드를 본문 추가하여 클라이언트에 응답?
-  mResponse.addHead("Content-Type", ~~~) 파일 확장자에 따라 매핑되는 내용으로 수정
    - jpg, jpeg mime.type Map에 추가
    - 업로드 되는 파일의 확장자도 확인하여 헤더를 변경하는 로직 필요
- ✭ 웹 브라우저에서 서버로부터 응답의 본문 내용도 리다이렉션할 때 포함해서 요청 해주는 지 확인 필요

[ 리다이렉션 후 파일 저장 ]
- Method - POST, Content-Length, Content-Type 확인하기
- ✭ MessageBody 파싱
   (현재 리다이렉션 요청 후 처리 결과)
![Image](https://github.com/gyuseuyunhu/server/assets/73283078/0aa6a6c7-2510-43d3-9c77-343ebab36cbe)
- ✭ 바이너리 코드(?)를 저장하는 함수 찾아보기

**Comment by guune** [comment]
- mResponse.addHead("Location", oss.str()) 부분에서 getHost()로 /upload 이면 addBody() 메서드를 통해 Form으로 받은 파일의 바이너리(?) 코드를 본문 추가하여 클라이언트에 응답?
- 클라이언트에 응답하는게 아닌 cgi에 넣어주면 될 것 같아요(지금 생각으로는)
