### ISSUE TITLE
server만들기를 어디서 할 것인가

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#6]
원래는 config가 서버를 만드는 메서드를 가지고 있고 그 메서드로 만들어서 서버 매니저 한테 넘겨줄려고 함
1. config에 서버 만드는 메서드 추가하기

그런데 servermanager가 addSevers로 해도 괜찮지 않을까 생각이듬

2.severmanager.
addSevers(Config & config) 

장점: config가 서버를 만들수 있어서 누구든지 서버를 만들수 있었는데 이 방법은 서버매니저만 서버를 만들수 있음
단점: 서버매니저의 역할이 커진다?

**Comment by heehoh** [comment]
server manager에서 하시죠
