### ISSUE TITLE
locatonBlock을 requset클래스 내부에서 만들어야 할까요?

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#62]
#### 1. Client-max-body size
-> 이제 post를 구현하면 body가 들어올텐데 contentLength의 경우 clientmaxbodysize보다 크면 에러
-> chunked면 body를 저장하다가 CMB보다 커지면 에러 반환이 필요해 보여요
#### 2. Method Deny(GET, POST ...)
-> method가 금지되어 있는지 확인이 필요하고요 금지되어 있으면 파싱을 끝까지 안해도 될것 같아요

#### 그래서 request파싱하고 host, path값만 있으면 locationBlock을 구할 수있으니 request 헤더 파싱하면서 locationBlock을 구하는것도 고려해봐야 할것 같아요

**Comment by heehoh** [comment]
그러면 로직이 좀 복잡해질 것 같은데 리퀘스트 다 파싱하고 그 후에 location 블록 확인해도 되지 않을까요

**Comment by guune** [comment]
> 그러면 로직이 좀 복잡해질 것 같은데 리퀘스트 다 파싱하고 그 후에 location 블록 확인해도 되지 않을까요

파싱할때 locatiobBlock의 내용이 필요해서요 위의 두가지 예도 파싱할때 확인해서 파싱을 그만두는 용도로 사용할 수 있을것 같아요
예를 들어서 locationBlock을 활용 안하면 chunked data를 0\r\n 들어올때까지 read를 해야되지만 읽다가 locationBlock의 clientMaxBody를 초과하면 더이상 안읽어도 되고요

두번째 예시의 경우 메서드가 허용 안되어 있으면 바로 에러 리턴하면 될것 같아요
핵심은 시작줄만 파싱해서  바로 에러 리턴이 가능해진다입니다
