### ISSUE TITLE
"if url /kapouet is rooted to /tmp/www, url /kapouet/pouic/toto/pouet is /tmp/www/pouic/toto/pouet" 이게 지시어 root 인가 alias 인가

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#7]
https://nginx.org/en/docs/http/ngx_http_core_module.html

![Image](https://github.com/gyuseuyunhu/server/assets/108771739/40313a55-f8fa-4541-88c8-3409d8efe8ca)

![Image](https://github.com/gyuseuyunhu/server/assets/108771739/e3986921-940c-4447-bfc0-d9d05738ebc9)

**Comment by guune** [comment]
rooted라고 해서 root인줄 알았는데 이거 alias가 맞는거 같기도?

**Comment by heehoh** [comment]
일단 root로 생각하고 코딩
