### ISSUE TITLE
seige 테스트

### ISSUE THREAD

**Issue by YunjooCho** [gyuseuyunhu/server#73]
### seige 테스트 설정 방법
1. brew install siege 터미널에 입력하여 seige 설치
2. code ~/.siege/siege.conf 로 seige.conf 파일 vscode로 열기
3. connection = keep-alive 로 수정
4. siege -b 127.0.0.1:8088
5. ctrl + c 로 시그널 종료시키면 결과값 출력(Availability가 95% 이상이여야 함)

**Comment by heehoh** [comment]
<img width="549" alt="Screen Shot 2024-01-14 at 4 35 12 PM" src="https://github.com/gyuseuyunhu/server/assets/114281631/b71eabd2-b4fe-4f47-9883-6cabce89e0df">
#77 시작줄 파싱 고친 후로 성공 트랜잭션이 100% 되었습니다.
