### ISSUE TITLE
CGI PATH_INFO 해석

### ISSUE THREAD

**Issue by heehoh** [gyuseuyunhu/server#80]
- CGI PATH_INFO라는 환경변수 처리
- 선택적으로 스크립트를 호출한 HTTP 요청의 추가 경로 정보를 포함하고 있으며 CGI 스크립트로 해석할 경로를 지정합니다. PATH_INFO는 CGI 스크립트가 리턴할 자원 또는 하위 자원을 식별하며 스크립트 이름 뒤에 오지만 모든 조회 데이터 앞에 오는 URI 경로 부분에서 파생됩니다.( 출처 [ibm](https://www.ibm.com/docs/ko/netcoolomnibus/8.1?topic=scripts-environment-variables-in-cgi-scriptl) )
- 위 문장을 나름대로 해석했을 때 PATH_INFO는 cgi extension 뒤에 / 경로가 더 있으면 그 경로를 넣어주는 변수인 것 같습니다.

**Comment by guune** [comment]
위의 해석대로 처리했습니다.
