### ISSUE TITLE
ERROR: 403 테스트 중 발생한 에러

### ISSUE THREAD

**Issue by heehoh** [gyuseuyunhu/server#81]
파일 권한이 없을 때 테스트를 위해 파일 권한을 없애고 테스트를 해봤습니다.

https://github.com/gyuseuyunhu/server/assets/114281631/2d7b5e9b-dd45-41df-a653-45ec9991cf8c

autoIndex가 켜져있어서 권한이 없을 때 목록을 보여주는데 보여주는 게 이상한 것 같습니다. Forbidden일 때는 autoIndex가 켜져 있어도 Forbidden 플래그를 유지해야 할 것 같아요.

더 이상한 거는 403 페이지를 하드코딩 안해서 없는데 페이지가 뜹니다. 아래 보면  assert로 막혀있는데
<img width="923" alt="Screen Shot 2024-01-14 at 8 01 20 PM" src="https://github.com/gyuseuyunhu/server/assets/114281631/2ee583da-0e58-4eca-9189-412694f0837e">

터미널에 찍어봤을 때 키가 403일 때 map value에 디렉토리 경로가 들어있습니다.
<img width="400" alt="Screen Shot 2024-01-14 at 8 01 26 PM" src="https://github.com/gyuseuyunhu/server/assets/114281631/f426633c-54fa-4a3c-91f7-9c407c8b7c23">

-fsanitize=address를 켜야 잘 막히고요.
<img width="905" alt="Screen Shot 2024-01-14 at 8 02 10 PM" src="https://github.com/gyuseuyunhu/server/assets/114281631/89189189-35bb-43eb-9852-c0634916cd09">

결론: 왜 그런지 모르겠는데 assert를 써도 안막히는 경우도 있는 듯 합니다.

**Comment by guune** [comment]
오타가 있었네요
    assert(it != mHttpErrorPages.end()); 이걸로 수정하시면 될 것 같습니다.
