### ISSUE TITLE
cgiExtension이 있는데 cgiPath가 없거나 유효하지 않을 때 에러처리

### ISSUE THREAD

**Issue by heehoh** [gyuseuyunhu/server#83]
- cgiPath가 유효한지 검증하는 로직이 없어서 추가를 해야하는데 어디에 추가를 해야 할까요?
  - conf 파일 에러로 처리하는 게 자연스러울 것 같긴 합니다.

**Comment by guune** [comment]
ReadRequestEvent클래스의 checkCgiEvent() 메소드에서 처리하도록 했습니다.
