### ISSUE TITLE
directive 클래스를 참고하는 sever, location block의 문제점

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#9]
Config가 directive클래스를 가지고 있다
Directive안에는 각각의 block의 지시어랑 중복 갯수를 맵형식으로 들고 있다(중복불가능하면 값이 1이라서 마이너스함으로써 중복을 체크)
이때 config에 하나만 존재할 수 있는 httpblock의 경우 문제가 안된다
하지만 여러개가 존재하는 다른 block들이 문제가 된다
예를 들어서 serverblock이 2개가 있고 각각 servername이 있으면 2번째 serverblock에서 servername 중복값이 0이돼서 에러가 뜬다

결국 원인은 각각의 block들이 각각의 directive 클래스안의 맵을 참고해야하는데 똑같은 맵을 참고해서 문제임

나랑 yunjcho님과 이야기 했을때 생각했던것은
1. 체크맵을 const로 보관하고 지시어체크를 할때마다 복사해서 넘겨주자(yunjcho)
장점: 실수로 부터 안전하다
단점: block마다 복사가 된다
2. 체크맵을 사용해서 지시어체크를 한 뒤 resetCheckmap같은것을 만들어서 reset을 하자(guune)
장점: 복사양이 적다
던점: reset함수를 사용자가 사용해야돼서 실수할수 있다

**Comment by guune** [comment]
클러스터 오면서 생각했던것
3. directive 클래스를 인터페이스로 만들고 checkStr또는 checkDrective를 만들어서 각각의 block들이 상속한다.

장점: 클래스 사용자가 reset을 안해도 된다(실수가 줄어듬), 1번방법과 같이 복사를 해야되지만 좀더 객체지향적임, 어떤 블록이든 checkStr로 돌리면 된다
단점: 지금은 config에서 block의 요소가 파싱 된다음 block의 생성자를 호출해서 만들었는데 이 구조를 변경해야됨
즉 각각의 block의 기본 생성자를 만들고 그 이후 복사연산자 오버로딩을 통해서 값을 넘겨줘야하는 형식으로(일단 block클래스를 만들어야 각 클래스의 checkStr 구조를 사용할 수 있다)  변경해야 된다

**Comment by guune** [comment]
클러스터 오면서 생각했던것
3. directive 클래스를 인터페이스로 만들고 checkStr또는 checkDrective를 만들어서 각각의 block들이 상속한다.

장점: 클래스 사용자가 reset을 안해도 된다(실수가 줄어듬), 1번방법과 같이 복사를 해야되지만 좀더 객체지향적임, 어떤 블록이든 checkStr로 돌리면 된다
단점: 지금은 config에서 block의 요소가 파싱 된다음 block의 생성자를 호출해서 만들었는데 이 구조를 변경해야됨
즉 각각의 block의 기본 생성자를 만들고 그 이후 복사연산자 오버로딩을 통해서 값을 넘겨줘야하는 형식으로(일단 block클래스를 만들어야 각 클래스의 checkStr 구조를 사용할 수 있다)  변경해야 된다

**Comment by guune** [comment]
4. 각각str클래스를 만든다 httpstr, serverstr, blockstr 
그 클래스들이 directive클래스를 상속받는다
장점: 3번의 단점
단점:parse 구조 뜯어고쳐야함

**Comment by guune** [comment]
5. 인터페이스로 할때 또 생각해야 될 것
- 그러면 checkMap을 누가 가지고 있을것인가
- 원래는 각각의 block들이 가지고 있었는데 클래스는 생성한 순간 유효해야 한다는 생각으로 directive 객체로 옮김
- 3번 방법을 하면 각각의 block들이 map을 들고 있어도 되는거 아닌가 싶음

**Comment by heehoh** [comment]
6. directive클래스 없애고 block들이 맵을 private으로 들고 있고 각각의 block에 checkStr메서드를 만들자
장점: 복잡한 인터페이스 쓸모 없음
단점: 클래스가 생성한 순간 유효한게 아님?.

**Comment by guune** [comment]
음… 결국 복사가 필요한 것이고 3,4,5,6 번 모두 어차피 복사를 어떻게 할것인가에 대한 방법 이야기 였다.
1번의 방식이 다 변형된 예시였다.
생각을 다시 해보고 코딩도 해보니 
httpDirective, ServerDirective, LocationDirective를 만들고 각각 check 맵을 들고 있으며 각각 checkStr을 들고 있게 하면 될듯
물론 복사문제는 해결이 안됐지만 "클래스가 생성한 순간 유효한게 아님"의 문제는 해결할 수 있다.

지금 현재로는 복사 문제 + 클래스 생성한 순간 유효 문제 + 실수 방지
다 만족하는 방법은 찾지 못했다.
다시 생각 나면 이슈 열겠습니다.
