### ISSUE TITLE
Timer 이벤트

### ISSUE THREAD

**Issue by heehoh** [gyuseuyunhu/server#92]
- Timer 이벤트를 구현하려고 합니다.
- 모든 이벤트에 타이머를 설정할 필요는 없을 것 같아서 필요한 이벤트만 해주면 될 것 같아요.
- Accept 이벤트는 타이머를 넣어줄 필요가 없을 것 같고,
- ReadReqeusetEvent는 타임아웃 되면 응답을 보내주지 않고 소켓만 닫아주면 될 것 같아요. 
  - ReadRequestEvent가 타임아웃 됐다는 것은 요청이 오지 않은 것이니 응답을 보내주지 않고 소켓만 닫아주면 될 것 같아요.
- CGI 이벤트에서 타임아웃 된  것은 서버에서 뭔가 에러가 났다는 뜻이니까 500에러를 보내주면 될 것 같습니다.
- WriteEvent에서 타임아웃 될 경우는 없을 것 같아 Accept와 마찬가지로 처리하지 않을 예정입니다.

**Comment by sngsho** [comment]
[우수한 히로쿠의 개발자들](https://devcenter.heroku.com/articles/request-timeout)의 이야기를 들어보면 Requset는 500ms 미만으로 유지되어야 클라이언트에게 고품질의 서비스를 제공할 수 있다고 하네요.
