### ISSUE TITLE
CGI 환경변수 추가 및 처리

### ISSUE THREAD

**Issue by guune** [gyuseuyunhu/server#93]
- FileUpload랑 delete를 cgi로 처리하다 보니 cgi에 보내주는 환경변수를 추가 및 정리할 필요가 있을것 같습니다.
### 기본 환경변수들
- REQUEST_METHOD;
- SERVER_PROTOCOL;
- PATH_INFO;
를 넣어주고 있습니다.

필요한 환경변수랑 이유를 댓글로 달아주시면 될 것 같습니다.

**Comment by heehoh** [comment]
WEBSERV_ROOT가 필요합니다 -> 웹서버 루트를 기반으로 파일 위치를 찾기 때문입니다.
conf 파일에 CGI로 업로드 된 파일 경로가 포함되어야 할 것 같아요. 환경변수 이름은 아직 모르겠습니다.
PATH_INFO에 url에 cgi 경로 뒤에 오는 path를 넣어주면 될 것 같습니다.

**Comment by guune** [comment]
cgi_upload_dir를 conf에 추가 하고 cgi한테는 upload_dir 환경변수로 추가하겠습니다.

**Comment by guune** [comment]
정리를 하면 
환경변수: WEBSERV_ROOT,  UPLOAD_DIR,  PATH_INFO(수정)
